project:
  type: book
  output-dir: "../docs"
  
knitr:
  opts_chunk:
    fig.path: include/fig/

book:
  title: "Quarto Quirks"
  author: "Rick Gilmore"
  chapters:
    - index.qmd
    - meta.qmd
    - books.qmd
    - slides.qmd
    - sites.qmd
    - plots.qmd
    - diagrams.qmd
  repo-url: https://github.com/rogilmore/quarto-quirks
  repo-actions: [edit, issue]
  repo-subdir: src
    
format:
  html:
    theme: cosmo
    number-sections: false
    fig-align: center
    date-modified: last-modified
    bibliography: include/bib/refs.bib
    html-math-method: mathjax
