project:
  type: book
  output-dir: "../docs"

book:
  title: "Quarto Quirks"
  author: "Rick Gilmore"
  chapters:
    - index.qmd
    - meta.qmd
    - books.qmd
    - slides.qmd
    - sites.qmd
format:
  html:
    theme: cosmo
    number-sections: false
    fig-align: center
